# Generated by Django 5.0 on 2026-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
